import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/CommonLayout";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { Toaster } from "@/components/ui/toaster"
import SearchContextProvider from "@/components/SearchContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <SessionProviderWrapper>
        <SearchContextProvider>
        <CommonLayout >
        {children}
        </CommonLayout>
        </SearchContextProvider>
        </SessionProviderWrapper>
        <Toaster />
        </body>
    </html>
  );
}
